from core.entities import Webhook, ReportFile
from typing import Protocol


class WebhookProtocol(Protocol):
    def save(self, webhook: Webhook) -> bool: ...
    def load_all(self) -> list: ...
    # def delete(self, webhook: Webhook) -> None: ...


class FileProtocol(Protocol):
    def save(self, file: ReportFile) -> bool: ...
    def delete(self,file: ReportFile) -> None: ...
    def get_all(self) -> list: ...


